// This file has been generated by Py++.

#ifndef pairsdblib_free_functions_hpp__pyplusplus_wrapper
#define pairsdblib_free_functions_hpp__pyplusplus_wrapper

void register_free_functions();

#endif//pairsdblib_free_functions_hpp__pyplusplus_wrapper
