// This file has been generated by Py++.

#include "boost/python.hpp"

#include "boost/python/suite/indexing/vector_indexing_suite.hpp"

#include "includes.h"

#include "iostream"

#include "cstdio"

#include "modules/pairsdblib_free_functions.pypp.hpp"

#include "modules/vector_less__long_int__greater_.pypp.hpp"

#include "modules/vector_less__std_scope_pair_less_int_comma__int_greater___greater_.pypp.hpp"

namespace bp = boost::python;

BOOST_PYTHON_MODULE(pairsdblib){
    register_vector_less__std_scope_pair_less_int_comma__int_greater___greater__class();

    register_vector_less__long_int__greater__class();

    register_free_functions();
}

