// This file has been generated by Py++.

#include "boost/python.hpp"
#include "boost/python/suite/indexing/vector_indexing_suite.hpp"
#include "includes.h"
#include "iostream"
#include "cstdio"
#include "vector_less__std_scope_pair_less_int_comma__int_greater___greater_.pypp.hpp"

namespace bp = boost::python;

void register_vector_less__std_scope_pair_less_int_comma__int_greater___greater__class(){

    bp::class_< std::vector< std::pair<int, int> > >("vector_less__std_scope_pair_less_int_comma__int_greater___greater_")    
        .def( bp::vector_indexing_suite< ::std::vector< std::pair<int, int> > >() );

}
